### ISSUE TITLE
Release v1.1.0 on PyPi

### ISSUE THREAD

**Issue by tantale** [vrcmarcos/python-deprecated#6]
Hi Marcos,

Could you release the v1.1.0 on PyPi?

First, update your local repository:

```sh
git fetch origin master
git reset --hard v1.1.0
```

Release and push to PyPi

```sh
python setup.py release upload
```

**Comment by vrcmarcos** [comment]
Sure! I'm doing this right now!

**Comment by vrcmarcos** [comment]
Done! https://pypi.python.org/pypi/Python-Deprecated/1.1.0

**Comment by tantale** [comment]
Great!
