### ISSUE TITLE
python-deprecated vs deprecated

### ISSUE THREAD

**Issue by soxofaan** [vrcmarcos/python-deprecated#8]
Hi, I was exploring available options for a deprecation decorator in Python and found these (among others):
- "Python-Deprecated":  https://github.com/vrcmarcos/python-deprecated  (Pypi: https://pypi.org/project/Python-Deprecated/)
- "Deprecated": https://github.com/tantale/deprecated (Pypi: https://pypi.org/project/Deprecated/)

It seems both are pretty much the same.
As far as I understand "Deprecated" started as copy-paste of the code of "Python-Deprecated" in a new git repo (around Nov 2017).

If that is the case: wouldn't it be better to explicitly mark "Python-Deprecated" as deprecated (lol) and forward potential users to "Deprecated", both on github (e.g. in README) and on Pypi?

**Comment by tantale** [comment]
Marcos Cardoso holds the early versions of Python Deprecated, so he is the only one who can change the status of this project… as deprecated. Currently, only [Deprecated](https://pypi.org/project/Deprecated/) is under active development. The last version is v1.2.6.

**Comment by tantale** [comment]
Actually, I may be able to edit the README file… After holidays…

**Comment by vrcmarcos** [comment]
Hey,

Yeah, that's the story. @tantale started a new repo and this became the deprecated version of this lib.

Thanks for your PR! Just merged it :)
